spring:
  application:
    name: aiservice
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://14.225.254.190:5432/postgres
    username: my_user
    password: my_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    bootstrap-servers: ${SPRING_URL_KAFKA:localhost:9092}
    topic:
      name: apisearch

  servlet:
    multipart:
      enabled: true
      max-file-size: 2GB
      max-request-size: 2GB
server:
  port: 8081
app:
  upload:
    dir: uploads
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8070/eureka/}
    register-with-eureka: true
    fetch-registry: true