spring:
  application:
    name: aiservice
  zipkin:
    baseUrl: ${SPRING_ZIPKIN_BASE_URL:http://14.225.254.190:9411/api/v2/spans}
  datasource:
    url: ${SPRING_DB:jdbc:postgresql://14.225.254.190:5432/postgres}
    username: ${SPRING_DB_USER:my_user}
    password: ${SPRING_DB_PASSWORD:my_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    bootstrap-servers: ${SPRING_URL_KAFKA:localhost:9092}
    topic:
      name: apisearch

  servlet:
    multipart:
      enabled: true
      max-file-size: 2GB
      max-request-size: 2GB
server:
  port: 8081
app:
  upload:
    dir: uploads
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8070/eureka/}
    register-with-eureka: true
    fetch-registry: true
ai:
  text : ${MODEL_TEXT:qwen3:4b}
  embed : ${MODEL_EMBED:nomic-embed-text}
  host : ${MODEL_HOST:https://18184932427b.ngrok-free.app}

memory:
  domain : ${MEMORY_DOMAIN:14.225.254.190}
  port : ${MEMORY_PORT:5432}
  db : ${MEMORY_DB:postgres}
  username : ${MEMORY_USER_NAME:my_user}
  password : ${MEMORY_PASSWORD:my_password}
  table : ${MEMORY_TABLE:my_embeddings}

# cau hinh actuator
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  zipkin:
    tracing:
      endpoint: ${SPRING_ZIPKIN_BASE_URL:http://14.225.254.190:9411/api/v2/spans}
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    circuitbreakers:
      enabled: true
  info:
    env:
      enabled: true
