apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: userservice
  name: userservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: userservice
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        io.kompose.service: userservice
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: http://eurekaservice:8070/eureka/
            - name: SENTRY_DSN
              value: https://a95701bd885c17f6070f1369551276a2@o4509342987911168.ingest.de.sentry.io/4509342990401616
            - name: SENTRY_ENV
              value: dev
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://configserver:8071
            - name: SPRING_DATASOURCE_PASSWORD
              value: Rw3UXVo4jxlq24fSgA0t
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://14.225.254.190:3307/ThucTapTotNghiep?allowPublicKeyRetrieval=true&useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_ZIPKIN_BASE_URL
              value: http://14.225.254.190:9411/api/v2/spans
          image: doctorhoai/tttn_userservice:v3
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 9000
            initialDelaySeconds: 10    # chờ 10s mới check lần đầu
            periodSeconds: 5           # check mỗi 5s
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 9000
            initialDelaySeconds: 45
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 9000
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            requests:
              cpu: "500m"      # 0.5 core
              memory: "512Mi"  # 0.5GB
            limits:
              cpu: "1000m"     # 1 core
              memory: "1024Mi" # 1GB

          name: userservice
          ports:
            - containerPort: 9000
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: userservice
  name: userservice
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    io.kompose.service: userservice
