apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: apigateway
  name: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: apigateway
  template:
    metadata:
      labels:
        io.kompose.service: apigateway
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: http://eurekaservice:8070/eureka/
            - name: SENTRY_DSN
              value: https://a95701bd885c17f6070f1369551276a2@o4509342987911168.ingest.de.sentry.io/4509342990401616
            - name: SENTRY_ENV
              value: dev
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://configserver:8071
            - name: SPRING_ZIPKIN_BASE_URL
              value: http://14.225.254.190:9411/api/v2/spans
          image: doctorhoai/tttn_api:v1
          livenessProbe:
            exec:
              command:
                - curl --fail --silent http://localhost:6380/actuator/health/readiness | grep UP || exit 1
            failureThreshold: 20
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 6380
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
          name: apigateway
          ports:
            - containerPort: 6380
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: apigateway
  name: apigateway
spec:
  type: LoadBalancer
  ports:
    - name: "6380"
      port: 6380
      targetPort: 6380
  selector:
    io.kompose.service: apigateway