apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: apigateway
  name: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: apigateway
  template:
    metadata:
      labels:
        io.kompose.service: apigateway
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
              value: http://eurekaservice:8070/eureka/
            - name: SENTRY_DSN
              value: https://a95701bd885c17f6070f1369551276a2@o4509342987911168.ingest.de.sentry.io/4509342990401616
            - name: SENTRY_ENV
              value: dev
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://configserver:8071
            - name: SPRING_ZIPKIN_BASE_URL
              value: http://14.225.254.190:9411/api/v2/spans
          image: doctorhoai/tttn_api:v3
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 6380
            initialDelaySeconds: 10    # chờ 10s mới check lần đầu
            periodSeconds: 5           # check mỗi 5s
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 6380
            initialDelaySeconds: 45
            periodSeconds: 10
            failureThreshold: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 6380
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            requests:
              cpu: "500m"      # 0.5 core
              memory: "512Mi"  # 0.5GB
            limits:
              cpu: "1000m"     # 1 core
              memory: "1024Mi" # 1GB

          name: apigateway
          ports:
            - containerPort: 6380
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: apigateway
  name: apigateway
spec:
  type: LoadBalancer
  ports:
    - name: "6380"
      port: 6380
      targetPort: 6380
  selector:
    io.kompose.service: apigateway