groups:
  - name: service-health
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: 'Instance {{ $labels.instance }} down'
          description: 'Target has been down for > 2 minutes.'
